springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /docs

logging:
  level:
    org.springdoc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: mappings

server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://13.48.203.214:5432/neforiidb
    username: postgres
    password: parola
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update #momentan tinem pe update, dar pt productie ar trb sa fie none
#      show-sql: true
    properties:
      hibernate.format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

file-upload:
  ssh:
    key-path: C:\Users\Alexandra\Desktop\Neforii\ZTH-Database-key.pem
    username: ubuntu
    host: 13.48.203.214
    remote-dir: /home/ubuntu/images_uploads

